// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyQuayThuoc.Data;

#nullable disable

namespace QuanLyQuayThuoc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyQuayThuoc.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal?>("GiaBanTaiThoiDiem")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaDvt")
                        .HasColumnType("int")
                        .HasColumnName("MaDVT");

                    b.Property<int?>("MaLo")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaChiTiet")
                        .HasName("PK__ChiTietD__CDF0A114511AB443");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaDvt");

                    b.HasIndex("MaLo");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.ChiTietKiemKe", b =>
                {
                    b.Property<int>("MaPhieu")
                        .HasColumnType("int");

                    b.Property<int>("MaLo")
                        .HasColumnType("int");

                    b.Property<string>("LyDoLech")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SoLuongHeThong")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongThucTe")
                        .HasColumnType("int");

                    b.HasKey("MaPhieu", "MaLo")
                        .HasName("PK__ChiTietK__5412E395EA49E629");

                    b.HasIndex("MaLo");

                    b.ToTable("ChiTietKiemKe", (string)null);
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.ChuDeSucKhoe", b =>
                {
                    b.Property<int>("MaChuDe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuDe"));

                    b.Property<string>("NoiDungGiaiPhap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChuDe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TieuDePhu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaChuDe")
                        .HasName("PK__ChuDeSuc__3585451132964912");

                    b.ToTable("ChuDeSucKhoe", (string)null);
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.DanhMuc", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<string>("Icon")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDanhMuc")
                        .HasName("PK__DanhMuc__B3750887319BDF1A");

                    b.ToTable("DanhMuc", (string)null);
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonHang"));

                    b.Property<string>("AnhDonThuoc")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DiaChiGiaoHang")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoDienThoaiNhan")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDonHang")
                        .HasName("PK__DonHang__129584AD23635ABC");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.DonViTinh", b =>
                {
                    b.Property<int>("MaDvt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDVT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDvt"));

                    b.Property<decimal?>("GiaBan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("GiaTriQuyDoi")
                        .HasColumnType("int");

                    b.Property<bool?>("LaDonViCoBan")
                        .HasColumnType("bit");

                    b.Property<int?>("MaThuoc")
                        .HasColumnType("int");

                    b.Property<string>("TenDonVi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaDvt")
                        .HasName("PK__DonViTin__3D895AFE1BB90994");

                    b.HasIndex("MaThuoc");

                    b.ToTable("DonViTinh", (string)null);
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.GioHang", b =>
                {
                    b.Property<int>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGioHang"));

                    b.Property<int?>("MaDvt")
                        .HasColumnType("int")
                        .HasColumnName("MaDVT");

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaThuoc")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaGioHang")
                        .HasName("PK__GioHang__F5001DA37BAF0A6A");

                    b.HasIndex("MaDvt");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaThuoc");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.HinhAnhThuoc", b =>
                {
                    b.Property<int>("MaHinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHinh"));

                    b.Property<string>("DuongDan")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("MaThuoc")
                        .HasColumnType("int");

                    b.HasKey("MaHinh")
                        .HasName("PK__HinhAnhT__13EE10841389A792");

                    b.HasIndex("MaThuoc");

                    b.ToTable("HinhAnhThuoc", (string)null);
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.LichSuChatbot", b =>
                {
                    b.Property<int>("MaChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChat"));

                    b.Property<string>("CauHoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CauTraLoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaChat")
                        .HasName("PK__LichSuCh__1B56CB6B505800A4");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("LichSuChatbot", (string)null);
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.LoHang", b =>
                {
                    b.Property<int>("MaLo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLo"));

                    b.Property<decimal?>("GiaNhap")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly>("HanSuDung")
                        .HasColumnType("date");

                    b.Property<int?>("MaNhaCungCap")
                        .HasColumnType("int");

                    b.Property<int?>("MaThuoc")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgaySanXuat")
                        .HasColumnType("date");

                    b.Property<string>("SoLo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.HasKey("MaLo")
                        .HasName("PK__LoHang__2725C75608560B53");

                    b.HasIndex("MaThuoc");

                    b.ToTable("LoHang", (string)null);
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Hoạt động");

                    b.HasKey("MaNguoiDung")
                        .HasName("PK__NguoiDun__C539D762AE933BA2");

                    b.HasIndex("MaVaiTro");

                    b.HasIndex(new[] { "SoDienThoai" }, "UQ__NguoiDun__0389B7BD927BD88F")
                        .IsUnique()
                        .HasFilter("[SoDienThoai] IS NOT NULL");

                    b.HasIndex(new[] { "Email" }, "UQ__NguoiDun__A9D1053484A3F442")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.PhieuKiemKe", b =>
                {
                    b.Property<int>("MaPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieu"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayKiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Hoàn tất");

                    b.HasKey("MaPhieu")
                        .HasName("PK__PhieuKie__2660BFE0E83E705F");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("PhieuKiemKe", (string)null);
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.SoDiaChi", b =>
                {
                    b.Property<int>("MaDiaChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDiaChi"));

                    b.Property<string>("DiaChiChiTiet")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTenNguoiNhan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("LaMacDinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LoaiDiaChi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("PhuongXa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QuanHuyen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoaiNhan")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TinhThanh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDiaChi")
                        .HasName("PK__SoDiaChi__EB61213E0D918E59");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("SoDiaChi", (string)null);
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.Thuoc", b =>
                {
                    b.Property<int>("MaThuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThuoc"));

                    b.Property<string>("BaoQuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CachDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChongChiDinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CongDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DangBaoChe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DoiTuongSuDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HanSuDungThang")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnhChinh")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("LaThuocKeDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("LuotXem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("LuuY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<string>("MoTaNgan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NhaSanXuat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NuocSanXuat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QuyCach")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDangKy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TacDungPhu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThuoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ThanhPhan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaThuoc")
                        .HasName("PK__Thuoc__4BB1F6204ED9346A");

                    b.HasIndex("MaDanhMuc");

                    b.ToTable("Thuoc", (string)null);
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVaiTro")
                        .HasName("PK__VaiTro__C24C41CF09F311D4");

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("ThuocChuDe", b =>
                {
                    b.Property<int>("MaThuoc")
                        .HasColumnType("int");

                    b.Property<int>("MaChuDe")
                        .HasColumnType("int");

                    b.HasKey("MaThuoc", "MaChuDe")
                        .HasName("PK__Thuoc_Ch__48E9A271E8067EEA");

                    b.HasIndex("MaChuDe");

                    b.ToTable("Thuoc_ChuDe", (string)null);
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("QuanLyQuayThuoc.Models.DonHang", "MaDonHangNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDonHang")
                        .HasConstraintName("FK__ChiTietDo__MaDon__68487DD7");

                    b.HasOne("QuanLyQuayThuoc.Models.DonViTinh", "MaDvtNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDvt")
                        .HasConstraintName("FK__ChiTietDo__MaDVT__6A30C649");

                    b.HasOne("QuanLyQuayThuoc.Models.LoHang", "MaLoNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaLo")
                        .HasConstraintName("FK__ChiTietDon__MaLo__693CA210");

                    b.Navigation("MaDonHangNavigation");

                    b.Navigation("MaDvtNavigation");

                    b.Navigation("MaLoNavigation");
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.ChiTietKiemKe", b =>
                {
                    b.HasOne("QuanLyQuayThuoc.Models.LoHang", "MaLoNavigation")
                        .WithMany("ChiTietKiemKes")
                        .HasForeignKey("MaLo")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietKie__MaLo__60A75C0F");

                    b.HasOne("QuanLyQuayThuoc.Models.PhieuKiemKe", "MaPhieuNavigation")
                        .WithMany("ChiTietKiemKes")
                        .HasForeignKey("MaPhieu")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietKi__MaPhi__5FB337D6");

                    b.Navigation("MaLoNavigation");

                    b.Navigation("MaPhieuNavigation");
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.DonHang", b =>
                {
                    b.HasOne("QuanLyQuayThuoc.Models.NguoiDung", "MaKhachHangNavigation")
                        .WithMany("DonHangMaKhachHangNavigations")
                        .HasForeignKey("MaKhachHang")
                        .HasConstraintName("FK__DonHang__MaKhach__6383C8BA");

                    b.HasOne("QuanLyQuayThuoc.Models.NguoiDung", "MaNhanVienNavigation")
                        .WithMany("DonHangMaNhanVienNavigations")
                        .HasForeignKey("MaNhanVien")
                        .HasConstraintName("FK__DonHang__MaNhanV__6477ECF3");

                    b.Navigation("MaKhachHangNavigation");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.DonViTinh", b =>
                {
                    b.HasOne("QuanLyQuayThuoc.Models.Thuoc", "MaThuocNavigation")
                        .WithMany("DonViTinhs")
                        .HasForeignKey("MaThuoc")
                        .HasConstraintName("FK__DonViTinh__MaThu__5535A963");

                    b.Navigation("MaThuocNavigation");
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.GioHang", b =>
                {
                    b.HasOne("QuanLyQuayThuoc.Models.DonViTinh", "MaDvtNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaDvt")
                        .HasConstraintName("FK__GioHang__MaDVT__6EF57B66");

                    b.HasOne("QuanLyQuayThuoc.Models.NguoiDung", "MaKhachHangNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaKhachHang")
                        .HasConstraintName("FK__GioHang__MaKhach__6D0D32F4");

                    b.HasOne("QuanLyQuayThuoc.Models.Thuoc", "MaThuocNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaThuoc")
                        .HasConstraintName("FK__GioHang__MaThuoc__6E01572D");

                    b.Navigation("MaDvtNavigation");

                    b.Navigation("MaKhachHangNavigation");

                    b.Navigation("MaThuocNavigation");
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.HinhAnhThuoc", b =>
                {
                    b.HasOne("QuanLyQuayThuoc.Models.Thuoc", "MaThuocNavigation")
                        .WithMany("HinhAnhThuocs")
                        .HasForeignKey("MaThuoc")
                        .HasConstraintName("FK__HinhAnhTh__MaThu__52593CB8");

                    b.Navigation("MaThuocNavigation");
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.LichSuChatbot", b =>
                {
                    b.HasOne("QuanLyQuayThuoc.Models.NguoiDung", "MaKhachHangNavigation")
                        .WithMany("LichSuChatbots")
                        .HasForeignKey("MaKhachHang")
                        .HasConstraintName("FK__LichSuCha__MaKha__71D1E811");

                    b.Navigation("MaKhachHangNavigation");
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.LoHang", b =>
                {
                    b.HasOne("QuanLyQuayThuoc.Models.Thuoc", "MaThuocNavigation")
                        .WithMany("LoHangs")
                        .HasForeignKey("MaThuoc")
                        .HasConstraintName("FK__LoHang__MaThuoc__5812160E");

                    b.Navigation("MaThuocNavigation");
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.NguoiDung", b =>
                {
                    b.HasOne("QuanLyQuayThuoc.Models.VaiTro", "MaVaiTroNavigation")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro")
                        .HasConstraintName("FK__NguoiDung__MaVai__3B75D760");

                    b.Navigation("MaVaiTroNavigation");
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.PhieuKiemKe", b =>
                {
                    b.HasOne("QuanLyQuayThuoc.Models.NguoiDung", "MaNhanVienNavigation")
                        .WithMany("PhieuKiemKes")
                        .HasForeignKey("MaNhanVien")
                        .HasConstraintName("FK__PhieuKiem__MaNha__5BE2A6F2");

                    b.Navigation("MaNhanVienNavigation");
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.SoDiaChi", b =>
                {
                    b.HasOne("QuanLyQuayThuoc.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("SoDiaChis")
                        .HasForeignKey("MaNguoiDung")
                        .HasConstraintName("FK__SoDiaChi__MaNguo__403A8C7D");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.Thuoc", b =>
                {
                    b.HasOne("QuanLyQuayThuoc.Models.DanhMuc", "MaDanhMucNavigation")
                        .WithMany("Thuocs")
                        .HasForeignKey("MaDanhMuc")
                        .HasConstraintName("FK__Thuoc__MaDanhMuc__48CFD27E");

                    b.Navigation("MaDanhMucNavigation");
                });

            modelBuilder.Entity("ThuocChuDe", b =>
                {
                    b.HasOne("QuanLyQuayThuoc.Models.ChuDeSucKhoe", null)
                        .WithMany()
                        .HasForeignKey("MaChuDe")
                        .IsRequired()
                        .HasConstraintName("FK__Thuoc_Chu__MaChu__4F7CD00D");

                    b.HasOne("QuanLyQuayThuoc.Models.Thuoc", null)
                        .WithMany()
                        .HasForeignKey("MaThuoc")
                        .IsRequired()
                        .HasConstraintName("FK__Thuoc_Chu__MaThu__4E88ABD4");
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.DanhMuc", b =>
                {
                    b.Navigation("Thuocs");
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.DonViTinh", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("GioHangs");
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.LoHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietKiemKes");
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.NguoiDung", b =>
                {
                    b.Navigation("DonHangMaKhachHangNavigations");

                    b.Navigation("DonHangMaNhanVienNavigations");

                    b.Navigation("GioHangs");

                    b.Navigation("LichSuChatbots");

                    b.Navigation("PhieuKiemKes");

                    b.Navigation("SoDiaChis");
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.PhieuKiemKe", b =>
                {
                    b.Navigation("ChiTietKiemKes");
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.Thuoc", b =>
                {
                    b.Navigation("DonViTinhs");

                    b.Navigation("GioHangs");

                    b.Navigation("HinhAnhThuocs");

                    b.Navigation("LoHangs");
                });

            modelBuilder.Entity("QuanLyQuayThuoc.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
